on:
  push:
    branches:
      - master
    paths:
      - "config/*.keymap"
      - "config/**/*.dtsi"
      - "config/**/*.h"
      - "config/**/*.conf"
      - "config/**/*.yml"
      - "west.yml"
      - "build.yaml"
  pull_request:
    branches:
      - master
  workflow_dispatch:

name: Corne_ZMK_build

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: set now
        run: echo "NOW=$(date +'%Y.%m.%d.%H.%M')" >> $GITHUB_ENV

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: firmware
          path: firmware

      - name: Publish release
        uses: svenstaro/upload-release-action@v2
        with:
          file: firmware/*.uf2
          file_glob: true
          tag: ${{ env.NOW }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
